name: dd_api

channels:
  - nodefaults
  - memex
  - anaconda
  - vida-nyu
  
dependencies:
    - elasticsearch
    - supervisor
    - meld3
    - dateutil
    - cython >=0.22
    - ddt-word2vec
    - maven
    - nltk
    - scipy
    - numexpr >=2.4
    - scikit-learn >=0.18.1
    - pyelasticsearch >=1.2
    - cherrypy
    - requests
    - ache >=0.8.0
    - jinja2
    - bokeh=0.10.0
    - topik
    - functools32
    - networkx=1.11
    - nodejs
    - futures
